// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexUs.Data;

#nullable disable

namespace NexUs.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260206031902_UpdateRolesToSuperAdminAndAdmin")]
    partial class UpdateRolesToSuperAdminAndAdmin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NexUs.Models.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityMunicipality")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Postal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("StreetBarangay")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("NexUs.Models.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Audit_Logs", (string)null);
                });

            modelBuilder.Entity("NexUs.Models.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("Name", "Module")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 6, 3, 19, 1, 845, DateTimeKind.Utc).AddTicks(9233),
                            Description = "View user list and details",
                            Module = "Users",
                            Name = "ViewUsers",
                            UpdatedAt = new DateTime(2026, 2, 6, 3, 19, 1, 845, DateTimeKind.Utc).AddTicks(9234)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 6, 3, 19, 1, 845, DateTimeKind.Utc).AddTicks(9236),
                            Description = "Create new users",
                            Module = "Users",
                            Name = "CreateUsers",
                            UpdatedAt = new DateTime(2026, 2, 6, 3, 19, 1, 845, DateTimeKind.Utc).AddTicks(9236)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 6, 3, 19, 1, 845, DateTimeKind.Utc).AddTicks(9238),
                            Description = "Update existing users",
                            Module = "Users",
                            Name = "UpdateUsers",
                            UpdatedAt = new DateTime(2026, 2, 6, 3, 19, 1, 845, DateTimeKind.Utc).AddTicks(9238)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 6, 3, 19, 1, 845, DateTimeKind.Utc).AddTicks(9240),
                            Description = "Delete users",
                            Module = "Users",
                            Name = "DeleteUsers",
                            UpdatedAt = new DateTime(2026, 2, 6, 3, 19, 1, 845, DateTimeKind.Utc).AddTicks(9240)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 6, 3, 19, 1, 845, DateTimeKind.Utc).AddTicks(9242),
                            Description = "View role list and details",
                            Module = "Roles",
                            Name = "ViewRoles",
                            UpdatedAt = new DateTime(2026, 2, 6, 3, 19, 1, 845, DateTimeKind.Utc).AddTicks(9242)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 2, 6, 3, 19, 1, 845, DateTimeKind.Utc).AddTicks(9245),
                            Description = "Create new roles",
                            Module = "Roles",
                            Name = "CreateRoles",
                            UpdatedAt = new DateTime(2026, 2, 6, 3, 19, 1, 845, DateTimeKind.Utc).AddTicks(9246)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 2, 6, 3, 19, 1, 845, DateTimeKind.Utc).AddTicks(9247),
                            Description = "Update existing roles",
                            Module = "Roles",
                            Name = "UpdateRoles",
                            UpdatedAt = new DateTime(2026, 2, 6, 3, 19, 1, 845, DateTimeKind.Utc).AddTicks(9248)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 2, 6, 3, 19, 1, 845, DateTimeKind.Utc).AddTicks(9249),
                            Description = "Delete roles",
                            Module = "Roles",
                            Name = "DeleteRoles",
                            UpdatedAt = new DateTime(2026, 2, 6, 3, 19, 1, 845, DateTimeKind.Utc).AddTicks(9250)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 2, 6, 3, 19, 1, 845, DateTimeKind.Utc).AddTicks(9251),
                            Description = "View permission list and details",
                            Module = "Permissions",
                            Name = "ViewPermissions",
                            UpdatedAt = new DateTime(2026, 2, 6, 3, 19, 1, 845, DateTimeKind.Utc).AddTicks(9251)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 2, 6, 3, 19, 1, 845, DateTimeKind.Utc).AddTicks(9254),
                            Description = "Create new permissions",
                            Module = "Permissions",
                            Name = "CreatePermissions",
                            UpdatedAt = new DateTime(2026, 2, 6, 3, 19, 1, 845, DateTimeKind.Utc).AddTicks(9254)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 2, 6, 3, 19, 1, 845, DateTimeKind.Utc).AddTicks(9255),
                            Description = "Update existing permissions",
                            Module = "Permissions",
                            Name = "UpdatePermissions",
                            UpdatedAt = new DateTime(2026, 2, 6, 3, 19, 1, 845, DateTimeKind.Utc).AddTicks(9256)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 2, 6, 3, 19, 1, 845, DateTimeKind.Utc).AddTicks(9257),
                            Description = "Delete permissions",
                            Module = "Permissions",
                            Name = "DeletePermissions",
                            UpdatedAt = new DateTime(2026, 2, 6, 3, 19, 1, 845, DateTimeKind.Utc).AddTicks(9257)
                        });
                });

            modelBuilder.Entity("NexUs.Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 6, 3, 19, 1, 845, DateTimeKind.Utc).AddTicks(9090),
                            Description = "Super Administrator with unrestricted access to all system features",
                            Name = "Super Admin",
                            UpdatedAt = new DateTime(2026, 2, 6, 3, 19, 1, 845, DateTimeKind.Utc).AddTicks(9090)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 6, 3, 19, 1, 845, DateTimeKind.Utc).AddTicks(9092),
                            Description = "Administrator with full access to manage users, roles, and permissions",
                            Name = "Admin",
                            UpdatedAt = new DateTime(2026, 2, 6, 3, 19, 1, 845, DateTimeKind.Utc).AddTicks(9093)
                        });
                });

            modelBuilder.Entity("NexUs.Models.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("Role_Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            PermissionId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            PermissionId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            PermissionId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            PermissionId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            PermissionId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 11,
                            PermissionId = 11,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 12,
                            PermissionId = 12,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 13,
                            PermissionId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 14,
                            PermissionId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 15,
                            PermissionId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 16,
                            PermissionId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 17,
                            PermissionId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 18,
                            PermissionId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 19,
                            PermissionId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 20,
                            PermissionId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 21,
                            PermissionId = 9,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 22,
                            PermissionId = 10,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 23,
                            PermissionId = 11,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 24,
                            PermissionId = 12,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("NexUs.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Suffix")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("NexUs.Models.Entities.UserCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultPassword")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPasswordChanged")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastPasswordChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserCredentials", (string)null);
                });

            modelBuilder.Entity("NexUs.Models.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("User_Roles", (string)null);
                });

            modelBuilder.Entity("NexUs.Models.Entities.AuditLog", b =>
                {
                    b.HasOne("NexUs.Models.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexUs.Models.Entities.Permission", b =>
                {
                    b.HasOne("NexUs.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NexUs.Models.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("NexUs.Models.Entities.Role", b =>
                {
                    b.HasOne("NexUs.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NexUs.Models.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("NexUs.Models.Entities.RolePermission", b =>
                {
                    b.HasOne("NexUs.Models.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexUs.Models.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NexUs.Models.Entities.User", b =>
                {
                    b.HasOne("NexUs.Models.Entities.Address", "Address")
                        .WithMany("Users")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NexUs.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NexUs.Models.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Address");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("NexUs.Models.Entities.UserCredential", b =>
                {
                    b.HasOne("NexUs.Models.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("NexUs.Models.Entities.UserCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexUs.Models.Entities.UserRole", b =>
                {
                    b.HasOne("NexUs.Models.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexUs.Models.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexUs.Models.Entities.Address", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("NexUs.Models.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("NexUs.Models.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("NexUs.Models.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
