// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexUs.Data;

#nullable disable

namespace NexUs.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260214052907_AddRoomTable")]
    partial class AddRoomTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NexUs.Models.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityMunicipality")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Postal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("StreetBarangay")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("NexUs.Models.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Audit_Logs", (string)null);
                });

            modelBuilder.Entity("NexUs.Models.Entities.AuthActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Device")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("auth_activity_logs", (string)null);
                });

            modelBuilder.Entity("NexUs.Models.Entities.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ManagedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ManagedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Buildings", (string)null);
                });

            modelBuilder.Entity("NexUs.Models.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("NexUs.Models.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("Name", "Module")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7773),
                            Description = "View user list and details",
                            Module = "Users",
                            Name = "ViewUsers",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7773)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7777),
                            Description = "Create new users",
                            Module = "Users",
                            Name = "CreateUsers",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7777)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7779),
                            Description = "Update existing users",
                            Module = "Users",
                            Name = "UpdateUsers",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7779)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7781),
                            Description = "Delete users",
                            Module = "Users",
                            Name = "DeleteUsers",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7781)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7783),
                            Description = "View role list and details",
                            Module = "Roles",
                            Name = "ViewRoles",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7783)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7786),
                            Description = "Create new roles",
                            Module = "Roles",
                            Name = "CreateRoles",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7786)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7788),
                            Description = "Update existing roles",
                            Module = "Roles",
                            Name = "UpdateRoles",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7788)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7790),
                            Description = "Delete roles",
                            Module = "Roles",
                            Name = "DeleteRoles",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7790)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7792),
                            Description = "View permission list and details",
                            Module = "Permissions",
                            Name = "ViewPermissions",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7792)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7795),
                            Description = "Create new permissions",
                            Module = "Permissions",
                            Name = "CreatePermissions",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7795)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7797),
                            Description = "Update existing permissions",
                            Module = "Permissions",
                            Name = "UpdatePermissions",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7797)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7799),
                            Description = "Delete permissions",
                            Module = "Permissions",
                            Name = "DeletePermissions",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7799)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7801),
                            Description = "View audit log list and details",
                            Module = "AuditLog",
                            Name = "ViewAuditLogs",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7801)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7802),
                            Description = "View operation log list and details",
                            Module = "OperationLog",
                            Name = "ViewOperationLogs",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7803)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7804),
                            Description = "View building list and details",
                            Module = "Buildings",
                            Name = "ViewBuildings",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7805)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7806),
                            Description = "Create new buildings",
                            Module = "Buildings",
                            Name = "CreateBuildings",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7807)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7808),
                            Description = "Update existing buildings",
                            Module = "Buildings",
                            Name = "UpdateBuildings",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7808)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7811),
                            Description = "Delete buildings",
                            Module = "Buildings",
                            Name = "DeleteBuildings",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7811)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7812),
                            Description = "Archive (soft delete) users",
                            Module = "Users",
                            Name = "ArchiveUsers",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7813)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7814),
                            Description = "Restore archived users",
                            Module = "Users",
                            Name = "RestoreUsers",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7815)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7816),
                            Description = "Permanently delete users",
                            Module = "Users",
                            Name = "PermanentDeleteUsers",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7817)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7818),
                            Description = "Archive (soft delete) roles",
                            Module = "Roles",
                            Name = "ArchiveRoles",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7818)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7820),
                            Description = "Restore archived roles",
                            Module = "Roles",
                            Name = "RestoreRoles",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7820)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7822),
                            Description = "Permanently delete roles",
                            Module = "Roles",
                            Name = "PermanentDeleteRoles",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7822)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7823),
                            Description = "Archive (soft delete) permissions",
                            Module = "Permissions",
                            Name = "ArchivePermissions",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7824)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7825),
                            Description = "Restore archived permissions",
                            Module = "Permissions",
                            Name = "RestorePermissions",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7826)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7827),
                            Description = "Permanently delete permissions",
                            Module = "Permissions",
                            Name = "PermanentDeletePermissions",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7827)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7830),
                            Description = "Archive (soft delete) buildings",
                            Module = "Buildings",
                            Name = "ArchiveBuildings",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7830)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7832),
                            Description = "Restore archived buildings",
                            Module = "Buildings",
                            Name = "RestoreBuildings",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7832)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7833),
                            Description = "Permanently delete buildings",
                            Module = "Buildings",
                            Name = "PermanentDeleteBuildings",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7834)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7835),
                            Description = "View room list and details",
                            Module = "Rooms",
                            Name = "ViewRooms",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7836)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7837),
                            Description = "Create new rooms",
                            Module = "Rooms",
                            Name = "CreateRooms",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7837)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7839),
                            Description = "Update existing rooms",
                            Module = "Rooms",
                            Name = "UpdateRooms",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7839)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7841),
                            Description = "Delete rooms",
                            Module = "Rooms",
                            Name = "DeleteRooms",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7842)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7843),
                            Description = "Archive (soft delete) rooms",
                            Module = "Rooms",
                            Name = "ArchiveRooms",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7844)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7845),
                            Description = "Restore archived rooms",
                            Module = "Rooms",
                            Name = "RestoreRooms",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7845)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7847),
                            Description = "Permanently delete rooms",
                            Module = "Rooms",
                            Name = "PermanentDeleteRooms",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7847)
                        });
                });

            modelBuilder.Entity("NexUs.Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7607),
                            Description = "Super Administrator with unrestricted access to all system features",
                            Name = "Super Admin",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7608)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7610),
                            Description = "Administrator with full access to manage users, roles, and permissions",
                            Name = "Admin",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7611)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7612),
                            Description = "Manages marketing operations and campaigns",
                            Name = "Marketing Manager",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7613)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7614),
                            Description = "Marketing team member",
                            Name = "Marketing Staff",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7615)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7616),
                            Description = "Manages building operations and maintenance",
                            Name = "Building Manager",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7616)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7618),
                            Description = "Educational staff member",
                            Name = "Teacher",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7618)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7626),
                            Description = "Team or project lead",
                            Name = "Lead",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7626)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7628),
                            Description = "External user or customer",
                            Name = "Customer",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(7628)
                        });
                });

            modelBuilder.Entity("NexUs.Models.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("Role_Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            PermissionId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            PermissionId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            PermissionId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            PermissionId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            PermissionId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 11,
                            PermissionId = 11,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 12,
                            PermissionId = 12,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 13,
                            PermissionId = 13,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 14,
                            PermissionId = 14,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 15,
                            PermissionId = 15,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 16,
                            PermissionId = 16,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 17,
                            PermissionId = 17,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 18,
                            PermissionId = 18,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 19,
                            PermissionId = 19,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 20,
                            PermissionId = 20,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 21,
                            PermissionId = 21,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 22,
                            PermissionId = 22,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 23,
                            PermissionId = 23,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 24,
                            PermissionId = 24,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 25,
                            PermissionId = 25,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 26,
                            PermissionId = 26,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 27,
                            PermissionId = 27,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 28,
                            PermissionId = 28,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 29,
                            PermissionId = 29,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 30,
                            PermissionId = 30,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 31,
                            PermissionId = 31,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 32,
                            PermissionId = 32,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 33,
                            PermissionId = 33,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 34,
                            PermissionId = 34,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 35,
                            PermissionId = 35,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 36,
                            PermissionId = 36,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 37,
                            PermissionId = 37,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 38,
                            PermissionId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 39,
                            PermissionId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 40,
                            PermissionId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 41,
                            PermissionId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 42,
                            PermissionId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 43,
                            PermissionId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 44,
                            PermissionId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 45,
                            PermissionId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 46,
                            PermissionId = 9,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 47,
                            PermissionId = 10,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 48,
                            PermissionId = 11,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 49,
                            PermissionId = 12,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 50,
                            PermissionId = 13,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 51,
                            PermissionId = 14,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 52,
                            PermissionId = 15,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 53,
                            PermissionId = 16,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 54,
                            PermissionId = 17,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 55,
                            PermissionId = 18,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 56,
                            PermissionId = 19,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 57,
                            PermissionId = 20,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 58,
                            PermissionId = 21,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 59,
                            PermissionId = 22,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 60,
                            PermissionId = 23,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 61,
                            PermissionId = 24,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 62,
                            PermissionId = 25,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 63,
                            PermissionId = 26,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 64,
                            PermissionId = 27,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 65,
                            PermissionId = 28,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 66,
                            PermissionId = 29,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 67,
                            PermissionId = 30,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 68,
                            PermissionId = 31,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 69,
                            PermissionId = 32,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 70,
                            PermissionId = 33,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 71,
                            PermissionId = 34,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 72,
                            PermissionId = 35,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 73,
                            PermissionId = 36,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 74,
                            PermissionId = 37,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("NexUs.Models.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("NexUs.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Suffix")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(8064),
                            Email = "digaljustin099@gmail.com",
                            FirstName = "Justin",
                            LastName = "Digal",
                            UpdatedAt = new DateTime(2026, 2, 14, 5, 29, 6, 732, DateTimeKind.Utc).AddTicks(8064)
                        });
                });

            modelBuilder.Entity("NexUs.Models.Entities.UserCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultPassword")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPasswordChanged")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastPasswordChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserCredentials", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsPasswordChanged = true,
                            PasswordHash = "$2a$12$69H2CbUh0/qNrS.4sheTRePxbeL1qmFiR9DLZydRbuo6Fm5Q6gy0O",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("NexUs.Models.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("User_Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("NexUs.Models.Entities.AuditLog", b =>
                {
                    b.HasOne("NexUs.Models.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexUs.Models.Entities.AuthActivityLog", b =>
                {
                    b.HasOne("NexUs.Models.Entities.User", "User")
                        .WithMany("AuthActivityLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexUs.Models.Entities.Building", b =>
                {
                    b.HasOne("NexUs.Models.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NexUs.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NexUs.Models.Entities.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NexUs.Models.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Address");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Manager");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("NexUs.Models.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("NexUs.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NexUs.Models.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NexUs.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexUs.Models.Entities.Permission", b =>
                {
                    b.HasOne("NexUs.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NexUs.Models.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("NexUs.Models.Entities.Role", b =>
                {
                    b.HasOne("NexUs.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NexUs.Models.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("NexUs.Models.Entities.RolePermission", b =>
                {
                    b.HasOne("NexUs.Models.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexUs.Models.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NexUs.Models.Entities.Room", b =>
                {
                    b.HasOne("NexUs.Models.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexUs.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NexUs.Models.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Building");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("NexUs.Models.Entities.User", b =>
                {
                    b.HasOne("NexUs.Models.Entities.Address", "Address")
                        .WithMany("Users")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NexUs.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NexUs.Models.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Address");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("NexUs.Models.Entities.UserCredential", b =>
                {
                    b.HasOne("NexUs.Models.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("NexUs.Models.Entities.UserCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexUs.Models.Entities.UserRole", b =>
                {
                    b.HasOne("NexUs.Models.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexUs.Models.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexUs.Models.Entities.Address", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("NexUs.Models.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("NexUs.Models.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("NexUs.Models.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("AuthActivityLogs");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
