// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexUs.Data;

#nullable disable

namespace NexUs.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260210024229_AddNewRoles")]
    partial class AddNewRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NexUs.Models.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityMunicipality")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Postal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("StreetBarangay")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("NexUs.Models.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Audit_Logs", (string)null);
                });

            modelBuilder.Entity("NexUs.Models.Entities.AuthActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Device")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("auth_activity_logs", (string)null);
                });

            modelBuilder.Entity("NexUs.Models.Entities.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ManagedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ManagedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Buildings", (string)null);
                });

            modelBuilder.Entity("NexUs.Models.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("NexUs.Models.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("Name", "Module")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2097),
                            Description = "View user list and details",
                            Module = "Users",
                            Name = "ViewUsers",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2098)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2104),
                            Description = "Create new users",
                            Module = "Users",
                            Name = "CreateUsers",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2105)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2107),
                            Description = "Update existing users",
                            Module = "Users",
                            Name = "UpdateUsers",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2107)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2108),
                            Description = "Delete users",
                            Module = "Users",
                            Name = "DeleteUsers",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2109)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2110),
                            Description = "View role list and details",
                            Module = "Roles",
                            Name = "ViewRoles",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2111)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2113),
                            Description = "Create new roles",
                            Module = "Roles",
                            Name = "CreateRoles",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2114)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2115),
                            Description = "Update existing roles",
                            Module = "Roles",
                            Name = "UpdateRoles",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2116)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2117),
                            Description = "Delete roles",
                            Module = "Roles",
                            Name = "DeleteRoles",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2118)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2119),
                            Description = "View permission list and details",
                            Module = "Permissions",
                            Name = "ViewPermissions",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2119)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2122),
                            Description = "Create new permissions",
                            Module = "Permissions",
                            Name = "CreatePermissions",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2122)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2124),
                            Description = "Update existing permissions",
                            Module = "Permissions",
                            Name = "UpdatePermissions",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2124)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2125),
                            Description = "Delete permissions",
                            Module = "Permissions",
                            Name = "DeletePermissions",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2126)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2127),
                            Description = "View audit log list and details",
                            Module = "AuditLog",
                            Name = "ViewAuditLogs",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2128)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2129),
                            Description = "View operation log list and details",
                            Module = "OperationLog",
                            Name = "ViewOperationLogs",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2129)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2131),
                            Description = "View building list and details",
                            Module = "Buildings",
                            Name = "ViewBuildings",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2131)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2133),
                            Description = "Create new buildings",
                            Module = "Buildings",
                            Name = "CreateBuildings",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2133)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2135),
                            Description = "Update existing buildings",
                            Module = "Buildings",
                            Name = "UpdateBuildings",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2135)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2137),
                            Description = "Delete buildings",
                            Module = "Buildings",
                            Name = "DeleteBuildings",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2137)
                        });
                });

            modelBuilder.Entity("NexUs.Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(1951),
                            Description = "Super Administrator with unrestricted access to all system features",
                            Name = "Super Admin",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(1951)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(1954),
                            Description = "Administrator with full access to manage users, roles, and permissions",
                            Name = "Admin",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(1954)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(1956),
                            Description = "Manages marketing operations and campaigns",
                            Name = "Marketing Manager",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(1956)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(1957),
                            Description = "Marketing team member",
                            Name = "Marketing Staff",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(1958)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(1959),
                            Description = "Manages building operations and maintenance",
                            Name = "Building Manager",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(1960)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(1961),
                            Description = "Educational staff member",
                            Name = "Teacher",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(1962)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(1968),
                            Description = "Team or project lead",
                            Name = "Lead",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(1969)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(1970),
                            Description = "External user or customer",
                            Name = "Customer",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(1971)
                        });
                });

            modelBuilder.Entity("NexUs.Models.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("Role_Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            PermissionId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            PermissionId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            PermissionId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            PermissionId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            PermissionId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 11,
                            PermissionId = 11,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 12,
                            PermissionId = 12,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 13,
                            PermissionId = 13,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 14,
                            PermissionId = 14,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 15,
                            PermissionId = 15,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 16,
                            PermissionId = 16,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 17,
                            PermissionId = 17,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 18,
                            PermissionId = 18,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 19,
                            PermissionId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 20,
                            PermissionId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 21,
                            PermissionId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 22,
                            PermissionId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 23,
                            PermissionId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 24,
                            PermissionId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 25,
                            PermissionId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 26,
                            PermissionId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 27,
                            PermissionId = 9,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 28,
                            PermissionId = 10,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 29,
                            PermissionId = 11,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 30,
                            PermissionId = 12,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 31,
                            PermissionId = 13,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 32,
                            PermissionId = 14,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 33,
                            PermissionId = 15,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 34,
                            PermissionId = 16,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 35,
                            PermissionId = 17,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 36,
                            PermissionId = 18,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("NexUs.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Suffix")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2360),
                            Email = "digaljustin099@gmail.com",
                            FirstName = "Justin",
                            LastName = "Digal",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 42, 28, 985, DateTimeKind.Utc).AddTicks(2360)
                        });
                });

            modelBuilder.Entity("NexUs.Models.Entities.UserCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultPassword")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPasswordChanged")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastPasswordChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserCredentials", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsPasswordChanged = true,
                            PasswordHash = "$2a$12$8p8vo9NFICWzOT5.fLh3AuJDTzjhtSFN1vPO31PrR6kdwEo11vi3G",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("NexUs.Models.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("User_Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("NexUs.Models.Entities.AuditLog", b =>
                {
                    b.HasOne("NexUs.Models.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexUs.Models.Entities.AuthActivityLog", b =>
                {
                    b.HasOne("NexUs.Models.Entities.User", "User")
                        .WithMany("AuthActivityLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexUs.Models.Entities.Building", b =>
                {
                    b.HasOne("NexUs.Models.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NexUs.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NexUs.Models.Entities.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NexUs.Models.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Address");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Manager");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("NexUs.Models.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("NexUs.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NexUs.Models.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NexUs.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexUs.Models.Entities.Permission", b =>
                {
                    b.HasOne("NexUs.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NexUs.Models.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("NexUs.Models.Entities.Role", b =>
                {
                    b.HasOne("NexUs.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NexUs.Models.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("NexUs.Models.Entities.RolePermission", b =>
                {
                    b.HasOne("NexUs.Models.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexUs.Models.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NexUs.Models.Entities.User", b =>
                {
                    b.HasOne("NexUs.Models.Entities.Address", "Address")
                        .WithMany("Users")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NexUs.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NexUs.Models.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Address");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("NexUs.Models.Entities.UserCredential", b =>
                {
                    b.HasOne("NexUs.Models.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("NexUs.Models.Entities.UserCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexUs.Models.Entities.UserRole", b =>
                {
                    b.HasOne("NexUs.Models.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexUs.Models.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexUs.Models.Entities.Address", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("NexUs.Models.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("NexUs.Models.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("NexUs.Models.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("AuthActivityLogs");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
