// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexUs.Data;

#nullable disable

namespace NexUs.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260210024839_AddArchiveRestorePermissions")]
    partial class AddArchiveRestorePermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NexUs.Models.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityMunicipality")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Postal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("StreetBarangay")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("NexUs.Models.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Audit_Logs", (string)null);
                });

            modelBuilder.Entity("NexUs.Models.Entities.AuthActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Device")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("auth_activity_logs", (string)null);
                });

            modelBuilder.Entity("NexUs.Models.Entities.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ManagedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ManagedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Buildings", (string)null);
                });

            modelBuilder.Entity("NexUs.Models.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("NexUs.Models.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("Name", "Module")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9714),
                            Description = "View user list and details",
                            Module = "Users",
                            Name = "ViewUsers",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9715)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9722),
                            Description = "Create new users",
                            Module = "Users",
                            Name = "CreateUsers",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9722)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9724),
                            Description = "Update existing users",
                            Module = "Users",
                            Name = "UpdateUsers",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9725)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9726),
                            Description = "Delete users",
                            Module = "Users",
                            Name = "DeleteUsers",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9727)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9728),
                            Description = "View role list and details",
                            Module = "Roles",
                            Name = "ViewRoles",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9729)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9731),
                            Description = "Create new roles",
                            Module = "Roles",
                            Name = "CreateRoles",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9731)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9733),
                            Description = "Update existing roles",
                            Module = "Roles",
                            Name = "UpdateRoles",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9733)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9735),
                            Description = "Delete roles",
                            Module = "Roles",
                            Name = "DeleteRoles",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9735)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9737),
                            Description = "View permission list and details",
                            Module = "Permissions",
                            Name = "ViewPermissions",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9737)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9739),
                            Description = "Create new permissions",
                            Module = "Permissions",
                            Name = "CreatePermissions",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9739)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9741),
                            Description = "Update existing permissions",
                            Module = "Permissions",
                            Name = "UpdatePermissions",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9741)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9743),
                            Description = "Delete permissions",
                            Module = "Permissions",
                            Name = "DeletePermissions",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9743)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9745),
                            Description = "View audit log list and details",
                            Module = "AuditLog",
                            Name = "ViewAuditLogs",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9745)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9747),
                            Description = "View operation log list and details",
                            Module = "OperationLog",
                            Name = "ViewOperationLogs",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9747)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9749),
                            Description = "View building list and details",
                            Module = "Buildings",
                            Name = "ViewBuildings",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9749)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9750),
                            Description = "Create new buildings",
                            Module = "Buildings",
                            Name = "CreateBuildings",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9751)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9752),
                            Description = "Update existing buildings",
                            Module = "Buildings",
                            Name = "UpdateBuildings",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9753)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9755),
                            Description = "Delete buildings",
                            Module = "Buildings",
                            Name = "DeleteBuildings",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9755)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9757),
                            Description = "Archive (soft delete) users",
                            Module = "Users",
                            Name = "ArchiveUsers",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9757)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9759),
                            Description = "Restore archived users",
                            Module = "Users",
                            Name = "RestoreUsers",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9759)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9761),
                            Description = "Permanently delete users",
                            Module = "Users",
                            Name = "PermanentDeleteUsers",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9761)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9762),
                            Description = "Archive (soft delete) roles",
                            Module = "Roles",
                            Name = "ArchiveRoles",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9763)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9764),
                            Description = "Restore archived roles",
                            Module = "Roles",
                            Name = "RestoreRoles",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9765)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9766),
                            Description = "Permanently delete roles",
                            Module = "Roles",
                            Name = "PermanentDeleteRoles",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9767)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9768),
                            Description = "Archive (soft delete) permissions",
                            Module = "Permissions",
                            Name = "ArchivePermissions",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9768)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9770),
                            Description = "Restore archived permissions",
                            Module = "Permissions",
                            Name = "RestorePermissions",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9770)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9772),
                            Description = "Permanently delete permissions",
                            Module = "Permissions",
                            Name = "PermanentDeletePermissions",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9772)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9773),
                            Description = "Archive (soft delete) buildings",
                            Module = "Buildings",
                            Name = "ArchiveBuildings",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9774)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9775),
                            Description = "Restore archived buildings",
                            Module = "Buildings",
                            Name = "RestoreBuildings",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9776)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9777),
                            Description = "Permanently delete buildings",
                            Module = "Buildings",
                            Name = "PermanentDeleteBuildings",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9778)
                        });
                });

            modelBuilder.Entity("NexUs.Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9577),
                            Description = "Super Administrator with unrestricted access to all system features",
                            Name = "Super Admin",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9578)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9580),
                            Description = "Administrator with full access to manage users, roles, and permissions",
                            Name = "Admin",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9580)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9582),
                            Description = "Manages marketing operations and campaigns",
                            Name = "Marketing Manager",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9583)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9584),
                            Description = "Marketing team member",
                            Name = "Marketing Staff",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9584)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9586),
                            Description = "Manages building operations and maintenance",
                            Name = "Building Manager",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9586)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9588),
                            Description = "Educational staff member",
                            Name = "Teacher",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9588)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9593),
                            Description = "Team or project lead",
                            Name = "Lead",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9593)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9595),
                            Description = "External user or customer",
                            Name = "Customer",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9595)
                        });
                });

            modelBuilder.Entity("NexUs.Models.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("Role_Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            PermissionId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            PermissionId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            PermissionId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            PermissionId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            PermissionId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 11,
                            PermissionId = 11,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 12,
                            PermissionId = 12,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 13,
                            PermissionId = 13,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 14,
                            PermissionId = 14,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 15,
                            PermissionId = 15,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 16,
                            PermissionId = 16,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 17,
                            PermissionId = 17,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 18,
                            PermissionId = 18,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 19,
                            PermissionId = 19,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 20,
                            PermissionId = 20,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 21,
                            PermissionId = 21,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 22,
                            PermissionId = 22,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 23,
                            PermissionId = 23,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 24,
                            PermissionId = 24,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 25,
                            PermissionId = 25,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 26,
                            PermissionId = 26,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 27,
                            PermissionId = 27,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 28,
                            PermissionId = 28,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 29,
                            PermissionId = 29,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 30,
                            PermissionId = 30,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 31,
                            PermissionId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 32,
                            PermissionId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 33,
                            PermissionId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 34,
                            PermissionId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 35,
                            PermissionId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 36,
                            PermissionId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 37,
                            PermissionId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 38,
                            PermissionId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 39,
                            PermissionId = 9,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 40,
                            PermissionId = 10,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 41,
                            PermissionId = 11,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 42,
                            PermissionId = 12,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 43,
                            PermissionId = 13,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 44,
                            PermissionId = 14,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 45,
                            PermissionId = 15,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 46,
                            PermissionId = 16,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 47,
                            PermissionId = 17,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 48,
                            PermissionId = 18,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 49,
                            PermissionId = 19,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 50,
                            PermissionId = 20,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 51,
                            PermissionId = 21,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 52,
                            PermissionId = 22,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 53,
                            PermissionId = 23,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 54,
                            PermissionId = 24,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 55,
                            PermissionId = 25,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 56,
                            PermissionId = 26,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 57,
                            PermissionId = 27,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 58,
                            PermissionId = 28,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 59,
                            PermissionId = 29,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 60,
                            PermissionId = 30,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("NexUs.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Suffix")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9980),
                            Email = "digaljustin099@gmail.com",
                            FirstName = "Justin",
                            LastName = "Digal",
                            UpdatedAt = new DateTime(2026, 2, 10, 2, 48, 38, 603, DateTimeKind.Utc).AddTicks(9980)
                        });
                });

            modelBuilder.Entity("NexUs.Models.Entities.UserCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultPassword")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPasswordChanged")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastPasswordChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserCredentials", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsPasswordChanged = true,
                            PasswordHash = "$2a$12$jU4ysL6aBDv7FODSYc92R.Nxxb8Wr3AJA9/bfo1oSceGw4hkhiFj.",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("NexUs.Models.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("User_Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("NexUs.Models.Entities.AuditLog", b =>
                {
                    b.HasOne("NexUs.Models.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexUs.Models.Entities.AuthActivityLog", b =>
                {
                    b.HasOne("NexUs.Models.Entities.User", "User")
                        .WithMany("AuthActivityLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexUs.Models.Entities.Building", b =>
                {
                    b.HasOne("NexUs.Models.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NexUs.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NexUs.Models.Entities.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NexUs.Models.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Address");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Manager");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("NexUs.Models.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("NexUs.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NexUs.Models.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NexUs.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexUs.Models.Entities.Permission", b =>
                {
                    b.HasOne("NexUs.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NexUs.Models.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("NexUs.Models.Entities.Role", b =>
                {
                    b.HasOne("NexUs.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NexUs.Models.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("NexUs.Models.Entities.RolePermission", b =>
                {
                    b.HasOne("NexUs.Models.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexUs.Models.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NexUs.Models.Entities.User", b =>
                {
                    b.HasOne("NexUs.Models.Entities.Address", "Address")
                        .WithMany("Users")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NexUs.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NexUs.Models.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Address");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("NexUs.Models.Entities.UserCredential", b =>
                {
                    b.HasOne("NexUs.Models.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("NexUs.Models.Entities.UserCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexUs.Models.Entities.UserRole", b =>
                {
                    b.HasOne("NexUs.Models.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexUs.Models.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexUs.Models.Entities.Address", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("NexUs.Models.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("NexUs.Models.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("NexUs.Models.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("AuthActivityLogs");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
